# Konfiguracja pluginu ZelekOgloszenia

# Nazwa serwera do wstawienia w wiadomościach (w cudzysłowie)
server-name: "MojSerwer"

# Ustawienia TITLE
announcement:
  fadeIn: 10    # czas pojawiania się tytułu (ticki)
  stay: 70      # czas wyświetlania tytułu (ticki)
  fadeOut: 20   # czas zanikania tytułu (ticki)
